### ISSUE TITLE
Get Tags on Message Detail Page

### ISSUE THREAD

**Issue by wesgate** [CrossingsCommunityChurch/RockTheme#29]
We can assign tags to a sermon easily, however, they don't seem to show as properties on the Item when viewing the 'Details' page

**Comment by wesgate** [comment]
Always get 'rockentity' is not configured for this template. I assume there is a way to allow a rockentity to be assigned to a template, but I am not sure how. We need to capture tags and I was doing that by using the entity for 'tag'

**Comment by wesgate** [comment]
@racingcow 

This is in messageDetails.lava

Displayed as an example on this page http://localhost:50886/media/a-church-that-reconciles

This is the next part I need some help tackling. The message has tags assigned to it (if you go to Content Channels Sermon Messages and edit a message you can see where the tags are assigned). I can manage to get the tag category id from the message and pull all the tags for that ID in messageDetails.lava, but i can't seem to figure out where the tags for that specific message are stored or are available.

In the template, we have an area to display them (and you will see me iterating over them in that messageDetails.lava page):

![tags_front](https://user-images.githubusercontent.com/3476357/86537371-286f6080-beb4-11ea-87ac-a1a29cfb4bfb.jpg)

but we of course only want to show the ones that are assigned to that particular message. We also need to eventually be able to query based on these tags on the /media page. First things first though is just figuring out where or how those tags are tied to the message and how we can go about getting them

Let me know if you have any questions on that

Wes

**Comment by camrun91** [comment]
<img width="510" alt="Screen Shot 2020-07-06 at 9 03 39 AM" src="https://user-images.githubusercontent.com/16566029/86601999-a9d3fb00-bf67-11ea-96c8-68f1516033d5.png">
This is what Newspring is doing for tags.

**Comment by racingcow** [comment]
Thanks, @camrun91. That's really helpful. One thing that concerns me about writing SQL to do stuff like this is that if the structure of the database ever changes with future versions, upgrading to a newer version of Rock would break lava shortcodes that depend on the old structure. Crossings would either need to do a bunch of recoding to upgrade or be stuck in an old version.

I'm not sure how likely the schema would be to change in future versions, but I've seen it happen in other projects. Having said that, if you guys think we should go with T-SQL, let me know and I'll head that direction. Otherwise I'll see if there is some Entity-related way to do it, and maybe we can find a way to make it faster later if it is too slow.

Another possible option would be to create our own View or Stored Procedure inside of SQL server, and then code against that. Then the db structure changes, we (or Crossings or whoever maintains it) would only have to change the layer of abstraction in  between.

**Comment by wesgate** [comment]
@camrun91 @racingcow

I would try the entity way first and see if you can get that to work, but if it ends up being a lot of trouble, just go with the SQL way. Obviously, we will just have to be cautious about upgrades in that case

Thanks!
Wes

**Comment by racingcow** [comment]
@wesgate @camrun91 Okay. Pull request is up for review now. Let me know if you see anything fishy.

**Comment by camrun91** [comment]
OK I have pulled the latest over to production. Just need to set up the changes that we made.
