### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by camrun91** [CrossingsCommunityChurch/RockTheme#48]
Need to set up events.

**Comment by camrun91** [comment]
Gene is talking to Matt and Jenniffer about if we want a calendar or just the events listed as cards.

**Comment by camrun91** [comment]
Just for documentation's sake, we have the events pulling on the location page for OKC. Need to change the shortcode to accept campusid param to make it useable on both campus pages. also need to limit how many are shown and make it a Carasoule. @wesgate Do we currently have a shortcode or anything to do this? It may also be good to do this with connection opportunities.

**Comment by wesgate** [comment]
There isn’t a carousel shortcode in the traditional sense (bootstrap technically has one that can be used), but if we follow how the prototype has those areas, it should keep all the cards stacked, 3 across and 3 rows (so up to 9 visilble) on desktop and then it will make them a single swipe-able row on mobile (which is a semi-carousel).

Wes

**Comment by camrun91** [comment]
@wesgate @racingcow I have pushed up the base for this stuff. there is still some work to do. David if you want to take a look at this and see if you can get some sort of filtering based on the "Audience" of the events on the locations page that would be awesome. I am thinking something like what they have here. https://hillsideonline.com/campus?campusId=2

That is if @wesgate doesn't have something else for you to look at.

**Comment by wesgate** [comment]
@racingcow Go for it, what Cameron is referring to is this part of their site:

![2020-07-21_16-01-28](https://user-images.githubusercontent.com/3476357/88107127-32f45000-cb6c-11ea-9698-b05ba4b9bea9.png)

They can filter the event list by Kids, Students, etc. What would be even nicer is if you could figure out a way to run the filter with and AJAX call or some way where we dont have to refresh the whole page

We have a similar component on our location pages:

![2020-07-21_16-07-44](https://user-images.githubusercontent.com/3476357/88107637-10166b80-cb6d-11ea-8b0f-ce6f8f1bd685.png)

The events are being pulled in from the location page. Events are added from Tools -> Calendars

On that AJAX front, maybe take a look at doing the pagination on the media page with an AJAX call as well?

Wes

@camrun91

**Comment by racingcow** [comment]
Sure, @wesgate and @camrun91 . I'll take a look at this tonight. Thanks!

**Comment by camrun91** [comment]
Yeah I like the sound of that. @wesgate the next step with the events I think is moving to a persisted dataset and limiting the events that are shown by default.

**Comment by racingcow** [comment]
Just a quick update from me on this. I've done some research, and for AJAX, [remote lava](https://community.rockrms.com/lava/remote-lava) that retrieves the results of SQL in a shortcode as a persisted dataset may be our best bet here. I just can't see any way to get the info we're looking for from the [API](http://localhost:50886/api/docs/index#!/EventCalendarItems/GETapi_EventCalendarItems) without making a bunch of calls in series.

There are maybe a couple of options...
1. Use an AJAX call as described above...
    * Write the SQL needed to retrieve all of the events occurring in the future that are active and approved
    * Let the page load normally, but don't load the events or load some minimal subset.
    * Have JS trigger on filter change to get the filtered current page of events
    * Render that on screen.
    * This one would make the user wait when he changes the filter.
2. Load everything up front...
    * Have the page load in every event item and render a variable in a JS script that contains all of the JSON for all of those items. 
    * On page load, the JS could deserialize that JSON into an object, and then just use that every time the filter changes. No AJAX calls would be required.
    * Changing the filter here would be near instantaneous since we don't have to go back to the server to get more data.
    * This could slow down the initial page load if the number of events get high, but I wouldn't think it would be significant unless there were hundreds of events being shown. We'd use a persisted data set here, and the only slowdown should be time to transfer the JSON along with the initial page load.

I think it's probably easiest to write this stuff in jQuery since that comes with Rock. We could try and shoehorn in some more modern JS framework, but that could be more complex.

Afterward I'd go back and AJAX-ify the media page with something similar to whichever solution we pick here.

I lean toward the second approach because it gives a faster filtering experience and I don't think the page slowdown will be that bad. I think we could make either work, though. Let me know if you have a preference, @wesgate and @camrun91. Otherwise I'll continue to head down path 2.

**Comment by camrun91** [comment]
I vote for #2 as well. I can work today on getting all the events into a persisted dataset. That should make the load of all events pretty quick especially if we cache the data. If the load starts to slow down we can only load events like a month out. I want to limit what is initially shown on the page anyways.

**Comment by wesgate** [comment]
@racingcow path 2 sounds good and yep, JQuery is probably the way to go with all of this stuff since it is already there

**Comment by camrun91** [comment]
I need to also look at seeing if I can get the details page to use the slug if it exists this will help with the search.

**Comment by racingcow** [comment]
I have some progress going now using jQuery to render the event cards. It isn't filtering or paging yet, though. I did notice that there were some errors in the `events` persisted dataset...

![image](https://user-images.githubusercontent.com/1176637/88451748-ec7a4c00-ce1e-11ea-965d-831a00f5c1be.png)

They were pretty minor (adding commas, stripping html), so I went ahead and fixed them. I put it in a new dataset called `events2` for now. Let me know if it's ok for me to replace `events` with `events2`.

@wesgate @camrun91

**Comment by wesgate** [comment]
@racingcow You should be fine to replace events with events2. Pretty sure the only place we are using the dataset is where you are working.

**Comment by camrun91** [comment]
Yes your good. I just got the dataset with the stuff I needed had not cleaned it up yet. We are not using it anywhere else yet.

**Comment by racingcow** [comment]
Okay. I've moved from `events2` to `events` and cleaned up all of my test `dmxxx` datasets. Client-side filtering is now working, and the events in the dataset (and, in turn, the cards on the events page) are displayed in the correct time order. 

I could not find a way, however, to also limit the number of sorted records being returned to the client. There's some kind of funky thing going on inside of Rock that prevents it from being able to serialize a single Event object, but will allow it to serialize an entire array of them. It's giving me the following error when I try and call the `ToJSON` filter on a single Event object in my array...

```Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.IConvertible```

The dataset does limit the results to only events that are `Active` and `Approved`. Would it be acceptable to train the admins to mark old events as Inactive if they start seeing slowdown loading the page in the future? If not, I could probably work around this by digging through the db structure to figure out the relationships and writing some SQL for this instead of lava event code.

One other question that I had... Do we want to do paging on the event cards on this page, or do we just want to limit to the upcoming N events on the client/server side (depending on the answer to the question above)?

**Comment by camrun91** [comment]
Today I will do some tests with event instances that have an old start date. I think if the event does not have any instances that are today or in the future it shouldn't show. If not I can add a date filter to the lava I think.

**Comment by wesgate** [comment]
@racingcow 

FYI - That error you are getting is the same thing Cameron ran into when creating the event list. There is a known bug in Rock where they had added asNoTracking() to everything and it broke some object references/properties:

https://github.com/SparkDevNetwork/Rock/issues/4293

Ideally, we would paginate it if we can (maybe just showing 6 at a time perhaps)

Wes

**Comment by camrun91** [comment]
Yes I think 6 at a time Would be good.

**Comment by racingcow** [comment]
Okay. I think I figured out how to sort everything by date, filter out any past events, and then limit the results to the N upcoming events.

I'll work on paging next.

**Comment by racingcow** [comment]
@wesgate @camrun91 ,

I think a good first stab at the functional stuff is ready with [this PR](https://github.com/CrossingsCommunityChurch/RockTheme/pull/62). Check it out when you have a chance and let me know if you have any questions or see things that should be changed, especially on resizing the images or other visual aspects.

I did notice that the old persisted dataset was building up a URL pointing to Cloudflare. I'm using the image URLs from Rock, though. Is our intent to use Cloudflare?

**Comment by camrun91** [comment]
It should be using a url that points to cloud front for images. There is a server that caches and re-sizes the images.

**Comment by wesgate** [comment]
@racingcow FYI - we got this merged in and took care of the image src

**Comment by racingcow** [comment]
Great, thanks @wesgate and @camrun91 . I should have said "Cloudfront" in my earlier post. Do you want me to change the media page to work in a similar way as part of this issue, or should we create another for that?

**Comment by wesgate** [comment]
@racingcow - yeah, let's create another issue for that. On that front, the dataset will be considerably larger for the media page. @camrun91 installed this plugin and it looks kind of interesting as a way to create REST endpoints:

https://www.blueboxmoon.com/plugin/data-toolkit/documentation/sql-endpoints

I was a little skeptical on the security side of this but it looks like you can define what types of requests you accept (GET, POST, etc), so we could lock it down to just GET. I am just wondering if we can use that or find an alternative to dumping the entire json object on the page for at least the media page. I know there would be a little bit of time in loading the request but I think it wouldn't be too bad to grab the items from an API call to populate the results

Create a new issue though and let me know what you think

**Comment by racingcow** [comment]
Okay, will do, @wesgate. I'll look at that plugin and/or find some way to do a true Ajax call on the media page.

**Comment by wesgate** [comment]
@racingcow - of course, all this talk of filtering and rest endpoints makes me really want to add vuejs to the project and just use it for the media listings. I know it adds some bloat but it may be worth considering. It's pretty much the lightest weight of its kind and only 35kb when gzipped and it could add some cool reactivity to the media page. Just running a little vue app for the media list essentially. You guys have any thoughts? i of course am a fan, but let me know if you think it's not a good idea.

**Comment by racingcow** [comment]
I think it's worth a shot, @wesgate. We could at least see how much work it would be, and could revert back to jQuery if it doesn't work out. Up to you guys, though.

**Comment by camrun91** [comment]
I am all for trying it.

**Comment by camrun91** [comment]
Is there any reason to leave this issue open @wesgate @racingcow?

**Comment by wesgate** [comment]
We can close it

Wes
