### ISSUE TITLE
Load more instead of paginating media listings

### ISSUE THREAD

**Issue by wesgate** [CrossingsCommunityChurch/RockTheme#76]

**Comment by wesgate** [comment]
@racingcow  - how hard would it be to have a "Load More" button instead of paginating the results on the media in that vue app?

**Comment by wesgate** [comment]
@racingcow - essentially just adding the next 9 to the list each time some clicks load more (rather than going backwards and forwards)

**Comment by racingcow** [comment]
@wesgate ,

I don't think it would be too hard. I'll take a look tonight.

**Comment by racingcow** [comment]
It looks like we'll need to modify the Defined Value for the Lava Webhook to take `skip` and `take` parameters, and then just loop between that range.

**Comment by racingcow** [comment]
Hey @wesgate ,

We wouldn't have to do the skip/take thing if we load everything up front like in [this PR](https://github.com/CrossingsCommunityChurch/RockTheme/pull/77). 

A couple of questions on this...
1. How do you feel about loading everything up front when the page loads like it is now? It will get slower over time on both server and client side (maybe only when/if it gets big enough to provide memory pressure on the server side). Alternatives on the server-side would be to restrict to the first N ordered media items like we do with events. On the client side the alternative would be to wrap some skip/take functionality around the persisted dataset and then have Vue load each set of 9 media items as needed from the server instead of loading everything at once.
2. I noticed that it will load media items that won't be activated until a future date. Maybe I should modify the persisted Combinedmedia dataset to only load media items that have an Activated data that is in the past?

**Comment by wesgate** [comment]
@racingcow -

On 1) it seems okay now, i know what you are saying but for now, i think it seems to work pretty well the way you have it

On 2) i think you are right and we need to maybe make sure the media items getting added are just the active ones that are in the past
